language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t myrkotyn/complex-react -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true myrkotyn/complex-react npm run test

after_success:
    - docker build -t myrkotyn/complex-client ./client
    - docker build -t myrkotyn/complex-nginx ./nginx
    - docker build -t myrkotyn/complex-api ./server
    - docker build -t myrkotyn/complex-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push myrkotyn/complex-client
    - docker push myrkotyn/complex-nginx
    - docker push myrkotyn/complex-api
    - docker push myrkotyn/complex-worker

deploy:
    provider: elasticbeansalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-717138922414"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
